<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_gallery"
 *
 * Auto generated by Extension Builder 2020-07-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Gallery',
    'description' => '',
    'category' => 'plugin',
    'author' => 'T3: Milan',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
