services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsGallery\:
    resource: '../Classes/*'

  NITSAN\NsGallery\Controller\NsConstantEditorController:
    public: true
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $sysTemplateRepository: '@TYPO3\CMS\Core\TypoScript\IncludeTree\SysTemplateRepository'
      $treeBuilder: '@TYPO3\CMS\Core\TypoScript\IncludeTree\SysTemplateTreeBuilder'
      $treeTraverser: '@TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\IncludeTreeTraverser'
      $astTraverser: '@TYPO3\CMS\Core\TypoScript\AST\Traverser\AstTraverser'
      $astBuilder: '@TYPO3\CMS\Core\TypoScript\AST\AstBuilderInterface'
      $losslessTokenizer: '@TYPO3\CMS\Core\TypoScript\Tokenizer\LosslessTokenizer'
      $nsGallleryBackendController: '@NITSAN\NsGallery\Controller\NsGalleryBackendController'
